# 本文件引用了苏白学堂的教学内容
# 学堂版拼音摘录自 [av11828488](https://www.bilibili.com/video/av11828488)
# 入门日常语摘录自 [av24054870](https://www.bilibili.com/video/av24054870)
# 侵权请联系我，我会第一时间删除

dict = 'https://wugniu.com/search?char={.word}&table=suzhou_zi'

[[rows]]
desc = '七声调（按调类）'
[rows.words]
'1' = '阴平44（金：cin1）'
'2' = '阳平223（琴：jin2）'
'3' = '上声51（紧：cin3）'
'5' = '阴去523（劲：cin5）'
'6' = '阳去231（近：jin6）'
'7' = '阴入43（急：ciq7）'
'8' = '阳入23（及：jiq8）'

[[rows]]
desc = '韵母a e i o'
[rows.words]
'a' = '[ɑ]'
'e' = '[e]'
'i' = '[i]'
'o' = '[o]'

[[rows]]
desc = '称呼（你、我、Ta...）'
[rows.words]
'我' = 'ngou6'
'你' = '（倷）ne6'
'Ta（两种发音）' = '（俚）li、唔倷 n ne'
'我们' = '（伲） gni6'
'你们' = '（唔笃） n toq'
'他们' = '（俚笃）li toq'

[[rows]]
desc = '打招呼（你好）'
[rows.words]
'你好！' = '（倷好！）ne hau'
'早上好！' = '（早浪好！）tsau laon hau'
'很久不见。' = '（长远弗见。）zan yoe feq cie'
'再见。' = '（再见）tse ue'
'一会见儿。' = '（晏歇会。）e shiq ue'
'明天见。' = '（明朝会。）men tsau ue'
