# 本文件引用了苏白学堂的教学内容
# 学堂版拼音摘录自 [av11828488](https://www.bilibili.com/video/av11828488)
# 入门日常语摘录自 [av24054870](https://www.bilibili.com/video/av24054870)
# 侵权请联系我，我会第一时间删除

dict = 'https://wugniu.com/search?char={.word}&table=suzhou_zi'

[[rows]]
desc = '七声调（按调类）'
[rows.words]
'1' = '阴平44（金：cin1）'
'2' = '阳平223（琴：jin2）'
'3' = '上声51（紧：cin3）'
'5' = '阴去523（劲：cin5）'
'6' = '阳去231（近：jin6）'
'7' = '阴入43（急：ciq7）'
'8' = '阳入23（及：jiq8）'

[[rows]]
desc = '韵母a e i o'
[rows.words]
'a' = '[ɑ]'
'e' = '[e]'
'i' = '[i]'
'o' = '[o]'

[[rows]]
desc = '韵母a e i o（拼读）'
[rows.words]
'挨 a1' = 'unavailable'
'矮 a3' = 'unavailable'
'a5' = 'unavailable'
'哀 e1' = 'unavailable'
'e3' = 'unavailable'
'爱 e5' = 'unavailable'
'衣 i1' = 'unavailable'
'移 yi2' = 'unavailable'
'椅 i3' = 'unavailable'
'意 i5' = 'unavailable'
'懿 yi6' = 'unavailable'
'蛙 o1' = 'unavailable'
'o3' = 'unavailable'
'o5' = 'unavailable'

[[rows]]
desc = '韵母au ie oe iu'
[rows.words]
'au' = '[æ]'
'ie' = '[iɪ]'
'oe' = '[ɸ]'
'iu' = '[y]'

[[rows]]
desc = '韵母au ie oe iu（拼读）'
[rows.words]
'凹 au1' = 'unavailable'
'襖 au3' = 'unavailable'
'澳 au5' = 'unavailable'
'烟 ie1' = 'unavailable'
'言 ye2' = 'unavailable'
'演 ie3' = 'unavailable'
'燕 ie5' = 'unavailable'
'械 ye6' = 'unavailable'
'安 oe1' = 'unavailable'
'oe3' = 'unavailable'
'芋 iu1' = 'unavailable'
'yu2' = 'unavailable'
'iu3' = 'unavailable'
'雨 iu5' = 'unavailable'
'yu6' = 'unavailable'

[[rows]]
desc = '声母p ph b'
[rows.words]
'p' = '[p]'
'ph' = '[ph]'
'b' = '[b]'

[[rows]]
desc = '声母p ph b（拼读）'
[rows.words]
'爸 pa1' = 'unavailable'
'pa3' = 'unavailable'
'湃 pa5' = 'unavailable'
'杯 pe1' = 'unavailable'
'板 pe3' = 'unavailable'
'輩 pe5' = 'unavailable'
'pi1' = 'unavailable'
'底 pi3' = 'unavailable'
'臂 pi5' = 'unavailable'
'疤 po1' = 'unavailable'
'靶 po3' = 'unavailable'
'霸 po5' = 'unavailable'
'邳 phe1' = 'unavailable'
'phe3' = 'unavailable'
'配 phe5' = 'unavailable'
'pho1' = 'unavailable'
'pho3' = 'unavailable'
'怕 pho5' = 'unavailable'
'牌 ba2' = 'unavailable'
'ba6' = 'unavailable'
'皮 bi2' = 'unavailable'
'币 bi6' = 'unavailable'
'扒 bo2' = 'unavailable'
'bo6' = 'unavailable'

[[rows]]
desc = '声母m f v'
[rows.words]
'm' = '[m]'
'f' = '[f]'
'v' = '[v]'

[[rows]]
desc = '声母m f v（拼读）'
[rows.words]
'煤 me2' = 'unavailable'
'妹 me6' = 'unavailable'
'麻 mo2' = 'unavailable'
'马 mo6' = 'unavailable'
'翻 fe1' = 'unavailable'
'反 fe3' = 'unavailable'
'販 fe5' = 'unavailable'
'飞 fi1' = 'unavailable'
'匪 fi3' = 'unavailable'
'沸 fi5' = 'unavailable'
'蜉 ve2' = 'unavailable'
'饭 ve6' = 'unavailable'

[[rows]]
desc = '整体认读音节pu puh bu fu vu'
[rows.words]
'u' = '[u]' # u 不单独发音

[[rows]]
desc = '整体认读音节pu puh bu fu vu（音调）'
[rows.words]
'玻 pu1' = 'unavailable'
'pu3' = 'unavailable'
'布 pu5' = 'unavailable'
'坡 phu1' = 'unavailable'
'圃 phu3' = 'unavailable'
'破 phu5' = 'unavailable'
'婆 bu2' = 'unavailable'
'部 bu6' = 'unavailable'
'夫 fu1' = 'unavailable'
'斧 fu3' = 'unavailable'
'付 fu5' = 'unavailable'
'舞 vu2' = 'unavailable'
'武 vu6' = 'unavailable'

[[rows]]
desc = '声母t th d'
[rows.words]
't' = '[t]'
'th' = '[tʰ]'
'd' = '[d]'

[[rows]]
desc = '声母t th d（拼读）'
[rows.words]
'刀 tau1' = 'unavailable'
'捣 tau3' = 'unavailable'
'到 tau5' = 'unavailable'
'巅 tie1' = 'unavailable'
'典 tie3' = 'unavailable'
'店 tie5' = 'unavailable'
'梯 thi1' = 'unavailable'
'体 thi3' = 'unavailable'
'替 thi5' = 'unavailable'
'天 thie1' = 'unavailable'
'舔 thie3' = 'unavailable'
'汏 da6' = 'unavailable'
'台 de2' = 'unavailable'
'蛋 de6' = 'unavailable'
'桃 dau2' = 'unavailable'
'道 dau6' = 'unavailable'
'团 doe2' = 'unavailable'
'段 doe6' = 'unavailable'

[[rows]]
desc = '声母n l'
[rows.words]
'n' = '[n]'
'l' = '[l]'

[[rows]]
desc = '声母n l（拼读）'
[rows.words]
'那 na1' = 'unavailable'
'奶 na6' = 'unavailable'
'囡 noe1' = 'unavailable'
'男 noe2' = 'unavailable'
'暖 noe6' = 'unavailable'
'雷 le2' = 'unavailable'
'儡 le3' = 'unavailable'
'懒 le6' = 'unavailable'
'俚 li1' = 'unavailable'
'梨 li2' = 'unavailable'
'屡 li3' = 'unavailable'
'里 li6' = 'unavailable'
'嘮 lau1' = 'unavailable'
'牢 lau2' = 'unavailable'
'lau3' = 'unavailable'
'老 lau6' = 'unavailable'
'莲 lie2' = 'unavailable'
'脸 lie3' = 'unavailable'
'练 lie6' = 'unavailable'


[[rows]]
desc = '声母k kh g ng'
[rows.words]
'k' = '[k]'
'kh' = '[kʰ]'
'g' = '[g]'
'ng' = '[ng]'

[[rows]]
desc = '声母k kh g ng（拼读）'
[rows.words]
'街 ka1' = 'unavailable'
'ka3' = 'unavailable'
'ka5' = 'unavailable'
'该 ke1' = 'unavailable'
'ke3' = 'unavailable'
'盖 ke5' = 'unavailable'
'瓜 ko1' = 'unavailable'
'ko5' = 'unavailable'
'糕 kau1' = 'unavailable'
'稿 kau3' = 'unavailable'
'告 kau5' = 'unavailable'
'kha1' = 'unavailable'
'卡 kha3' = 'unavailable'
'khau1' = 'unavailable'
'考 khau3' = 'unavailable'
'烤 khau5' = 'unavailable'
'茄 ga2' = 'unavailable'
'隑 ge6' = 'unavailable'
'牙 nga2' = 'unavailable'
'牙 nga2' = 'unavailable'


[[rows]]
desc = '称呼（你、我、Ta...）'
[rows.words]
'我' = 'ngou6'
'你' = '（倷）ne6'
'Ta（两种发音）' = '（俚）li、唔倷 n ne'
'我们' = '（伲） gni6'
'你们' = '（唔笃） n toq'
'他们' = '（俚笃）li toq'

[[rows]]
desc = '打招呼（你好）'
[rows.words]
'你好！' = '（倷好！）ne hau'
'早上好！' = '（早浪好！）tsau laon hau'
'很久不见。' = '（长远弗见。）zan yoe feq cie'
'再见。' = '（再见）tse ue'
'一会见儿。' = '（晏歇会。）e shiq ue'
'明天见。' = '（明朝会。）men tsau ue'
