name: Go release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Release
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - aix
          - android
          - darwin
          - dragonfly
          - freebsd
          - illumos
          - js
          - linux
          - netbsd
          - openbsd
          - plan9
          - solaris
          - wasip1
          - windows
        arch:
          - amd64
          - arm64
          - '386'
        exclude:
          - os: aix
            arch: amd64
          - os: aix
            arch: arm64
          - os: aix
            arch: '386'

          - os: android
            arch: amd64
          - os: android
            arch: '386'

          - os: darwin
            arch: '386'

          - os: dragonfly
            arch: arm64
          - os: dragonfly
            arch: '386'

          - os: illumos
            arch: '386'
          - os: illumos
            arch: arm64

          - os: js
            arch: '386'
          - os: js
            arch: amd64
          - os: js
            arch: arm64

          - os: plan9
            arch: arm64

          - os: solaris
            arch: arm64
          - os: solaris
            arch: '386'

          - os: wasip1
            arch: amd64
          - os: wasip1
            arch: arm64
          - os: wasip1
            arch: '386'
        include:
          - os: aix
            arch: ppc64

          - os: freebsd
            arch: arm
            arm: '7'
          - os: freebsd
            arch: arm
            arm: '6'
          - os: freebsd
            arch: arm
            arm: '5'

          - os: js
            arch: wasm

          - os: linux
            arch: arm
            arm: '7'
          - os: linux
            arch: arm
            arm: '6'
          - os: linux
            arch: arm
            arm: '5'
          - os: linux
            arch: loong64
          - os: linux
            arch: mips
          - os: linux
            arch: mips64
          - os: linux
            arch: mips64le
          - os: linux
            arch: mipsle
          - os: linux
            arch: ppc64
          - os: linux
            arch: ppc64le
          - os: linux
            arch: riscv64
          - os: linux
            arch: s390x

          - os: netbsd
            arch: arm
            arm: '7'
          - os: netbsd
            arch: arm
            arm: '6'
          - os: netbsd
            arch: arm
            arm: '5'

          - os: openbsd
            arch: arm
            arm: '7'
          - os: openbsd
            arch: arm
            arm: '6'
          - os: openbsd
            arch: arm
            arm: '5'
          - os: openbsd
            arch: ppc64
          - os: openbsd
            arch: riscv64

          - os: plan9
            arch: arm
            arm: '7'
          - os: plan9
            arch: arm
            arm: '6'
          - os: plan9
            arch: arm
            arm: '5'

          - os: wasip1
            arch: wasm

          - os: windows
            arch: arm
            arm: '7'
          - os: windows
            arch: arm
            arm: '6'
          - os: windows
            arch: arm
            arm: '5'
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      GOARM: ${{ matrix.arm }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build
        run: |
          if [ -n "$GOARM" ]; then
              ARCH_NAME=arm-v"$GOARM"
          elif [ "$GOARCH" = '386' ]; then
              ARCH_NAME='x86'
          elif [ "$GOARCH" = 'amd64' ]; then
              ARCH_NAME='x86_64'
          else
              ARCH_NAME="$GOARCH"
          fi
          
          if [ "$GOOS" == "windows" ]; then
              go build -o recitationcheck.exe
          else
              go build -o recitationcheck
          fi
          
          mkdir release-assets/
          if [ "$GOOS" = "windows" ]; then
              zip release-assets/recitationcheck-windows-$ARCH_NAME.zip recitationcheck.exe LICENSE NOTICE    
          else
              tar -zcf release-assets/recitationcheck-$GOOS-$ARCH_NAME.tar.gz recitationcheck LICENSE NOTICE
          fi
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*
